Repository fs/rails-base-graphql-api, pull requests merged in 2020-06, with the labels that each got.

#37 Use shared examples for GraphQL requests
  spec/fixtures/json/acceptance/graphql/query_type_me.json
  spec/fixtures/json/acceptance/graphql/signin.json
  spec/fixtures/json/acceptance/graphql/signin_wrong.json
  spec/fixtures/json/acceptance/graphql/signup.json
  spec/fixtures/json/acceptance/graphql/signup_wrong.json
  spec/fixtures/json/acceptance/graphql/update_user.json
  spec/graphql/mutations/sign_in_spec.rb
  spec/graphql/mutations/sign_up_spec.rb
  spec/graphql/mutations/update_user_spec.rb
  spec/graphql/types/query_type_me_spec.rb
  spec/rails_helper.rb
  spec/support/shared_examples/graphql_request.rb
Labels: enhancement

#49 Activity feed
  app/graphql/resolvers/activities.rb
  app/graphql/types/activity_type.rb
  app/graphql/types/query_type.rb
  app/interactors/create_register_activity.rb
  app/interactors/signup_user.rb
  app/models/activity.rb
  app/models/user.rb
  db/migrate/20200609122433_create_activities.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/activities.rb
  spec/factories/sequences.rb
  spec/fixtures/json/acceptance/graphql/query_type_activities.json
  spec/graphql/types/query_type_activity_spec.rb
  spec/interactors/create_register_activity_spec.rb
Labels: enhancement

#47 Fix sign up spec
  spec/graphql/mutations/sign_up_spec.rb
Labels: bug

#55 Add user reference to Activity query type
  app/graphql/types/activity_type.rb
  spec/fixtures/json/acceptance/graphql/query_type_activities.json
  spec/graphql/types/query_type_activity_spec.rb
Labels: enhancement

#54 Add Event attribute to Activities
  Gemfile
  Gemfile.lock
  app/graphql/types/activity_event_type.rb
  app/graphql/types/activity_type.rb
  app/interactors/create_register_activity.rb
  app/models/activity.rb
  config/initializers/strong_migrations.rb
  db/migrate/20200609122433_create_activities.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/activities.rb
  spec/fixtures/json/acceptance/graphql/query_type_activities.json
  spec/graphql/types/query_type_activity_spec.rb
  spec/interactors/create_register_activity_spec.rb
Labels: enhancement

#39 Make updateUser return user type
  access_token,
  app/graphql/mutations/update_user.rb
  refresh_token
  spec/fixtures/json/acceptance/graphql/update_token.json
  spec/fixtures/json/acceptance/graphql/update_token_failed.json
  spec/fixtures/json/acceptance/graphql/update_user.json
  spec/graphql/mutations/update_token_spec.rb
  spec/graphql/mutations/update_user_spec.rb
  {
Labels: bug, enhancement

#61 Decrease amount of queries on Activities
  Gemfile
  Gemfile.lock
  app/graphql/application_schema.rb
  app/graphql/loaders/association_loader.rb
  app/graphql/loaders/record_loader.rb
  app/graphql/types/activity_type.rb
  app/graphql/types/user_type.rb
Labels: enhancement

#34 Password recovery emails
  .env.example
  .semaphore/semaphore.yml
  Gemfile
  Gemfile.lock
  access_token,
  app/graphql/mutations/request_password_recovery.rb
  app/graphql/types/detailed_message_type.rb
  app/graphql/types/mutation_type.rb
  app/interactors/request_password_reset.rb
  app/mailers/application_mailer.rb
  app/models/user.rb
  app/views/application_mailer/password_recovery.html.erb
  app/views/application_mailer/password_recovery.text.erb
  app/views/layouts/mailer.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/action_mailer.rb
  config/locales/password_recovery.en.yml
  config/sidekiq.yml
  db/migrate/20200604082036_add_password_reset_token_to_users.rb
  db/schema.rb
  docker-compose.yml
  refresh_token
  spec/fixtures/json/acceptance/graphql/request_password_recovery.json
  spec/graphql/mutations/request_password_recovery_spec.rb
  spec/interactors/request_password_reset_spec.rb
  spec/mailers/application_mailer_spec.rb
  spec/mailers/previews/application_mailer_preview.rb
  spec/rails_helper.rb
  spec/support/shared_contexts/with_mail_delivery_stubbed.rb
  {
Labels: enhancement

#40 Update user password by reset password token
  app/forms/application_form.rb
  app/forms/update_user_form.rb
  app/forms/update_user_password_form.rb
  app/graphql/mutations/update_password.rb
  app/graphql/types/mutation_type.rb
  app/interactors/update_password.rb
  app/interactors/update_password/find_user_by_token.rb
  app/interactors/update_password/update_user_password.rb
  app/interactors/update_user.rb
  app/validators/existing_password_validator.rb
  app/validators/expiration_validator.rb
  config/initializers/locales.rb
  config/locales/models/update_user_password_form/en.yml
  spec/factories/users.rb
  spec/fixtures/json/acceptance/graphql/update_password.json
  spec/fixtures/json/acceptance/graphql/update_password_expired.json
  spec/fixtures/json/acceptance/graphql/update_password_wrong.json
  spec/graphql/mutations/update_password_spec.rb
  spec/interactors/update_password_spec.rb
  spec/validators/expiration_validator_spec.rb
Labels: enhancement

#56 Use Shrine for image uploading
  Gemfile
  Gemfile.lock
  app/graphql/mutations/presign_data.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/presign_field_type.rb
  app/graphql/types/presign_type.rb
  app/interactors/prepare_presign_image.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/shrine.rb
  spec/fixtures/json/acceptance/graphql/presign_data.json
  spec/fixtures/json/acceptance/graphql/presign_data_wrong.json
  spec/graphql/mutations/presign_data_spec.rb
  spec/interactors/prepare_presign_image_spec.rb
Labels: enhancement

#62 Update user avatar with uploaded data
  app/graphql/mutations/sign_up.rb
  app/graphql/mutations/update_user.rb
  app/graphql/types/image_uploader_metadata_type.rb
  app/graphql/types/image_uploader_type.rb
  app/graphql/types/user_type.rb
  app/models/user.rb
  app/uploaders/image_uploader.rb
  db/migrate/20200617151148_add_avatar_to_users.rb
  db/schema.rb
  spec/fixtures/images/avatar.jpg
  spec/fixtures/json/acceptance/graphql/signup.json
  spec/graphql/mutations/sign_up_spec.rb
Labels: enhancement
